# Generated by Django 3.0.5 on 2020-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dataset',
            new_name='x',
        ),
        migrations.AddField(
            model_name='data',
            name='y',
            field=models.CharField(default='zero', max_length=10000),
        ),
    ]
