# Generated by Django 3.0.5 on 2020-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20200429_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='testx',
            field=models.CharField(default='0', max_length=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='y',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
